uburelease: More verbosity in messages.

diff --git a/uburelease b/uburelease
--- a/uburelease
+++ b/uburelease
@@ -22,11 +22,16 @@
 set -e
 
 if [ ! -f /etc/ubumirror.conf ]; then
-	echo "File /etc/ubumirror.conf does not exist!"
-	exit
+    echo "File /etc/ubumirror.conf does not exist!"
+    exit 1
 fi
 
 . /etc/ubumirror.conf
+
+LOGFILE="$LOGDIR/uburelease.log"
+
+# Log all activity to file.
+exec >> $LOGFILE 2>&1
 
 if [ -z "$UBUREL_DIR" ]; then
     echo -n "No Ubuntu release target directory (UBUREL_DIR) set in "
@@ -36,38 +41,48 @@ fi
 
 LOCK="${UBUREL_DIR}/Archive-Update-in-Progress-${HOSTNAME}"
 
+trap 'rm -f $LOCK > /dev/null 2>&1; savelog -c 28 -n $LOGFILE > /dev/null' EXIT
+
 # Get in the right directory and set the umask to be group writable
 cd $HOME
 umask 022
 
+echo "$(date -R): Initiating Ubuntu release mirror operations..."
+
 # Check to see if another sync is in progress
 if ! ( set -o noclobber; echo "$$" > "${LOCK}") 2> /dev/null; then
-        if ! $(kill -0 $(cat ${LOCK}) 2>/dev/null); then
-                # Process does either not exist or is not owned by us.
-                echo "$$" > "${LOCK}"
-        else
-                echo "Unable to start rsync, lock file still exists, PID $(cat ${LOCK})."
-                exit 1
-        fi
+    if ! $(kill -0 $(cat ${LOCK}) 2>/dev/null); then
+        # Process does either not exist or is not owned by us.
+        echo "$$" > "${LOCK}"
+    else
+        echo "$(date -R): Unable to proceed with operations; lock file still exists for PID $(cat ${LOCK})."
+        exit 1
+    fi
 fi
 
-trap 'rm -f $LOCK > /dev/null 2>&1; echo "Done at $(date)" >> $LOGDIR/uburelease.log; savelog -c 28 -n $LOGDIR/uburelease.log > /dev/null' EXIT
-
-echo "Starting at $(date)" >> $LOGDIR/uburelease.log
+echo "$(date -R): Lock established for process $(cat ${LOCK})."
 
 set +e
-echo "Syncing ISOs..." >> $LOGDIR/uburelease.log
+echo "$(date -R): Syncing Ubuntu release CD images..."
+
 rsync -av --partial --timeout=600 --bwlimit=$SPEED --delete-after \
       --exclude .trace --exclude Archive-Update-in-Progress-* \
       $UBUREL_EXCLUDE \
-      $UBUREL_MIRROR $UBUREL_DIR >> $LOGDIR/uburelease.log 2>&1
+      $UBUREL_MIRROR $UBUREL_DIR
 
 if [ $? -ne 0 ]; then
-        ( echo "Eeek. Ubuntu iso rsync broke down... Check logs.."; \
-          egrep '^write failed|@ERROR' $LOGDIR/uburelease.log ) | mail -s "Ubuntu release sync failed" $EMAIL
-        echo "Eeek. Ubuntu iso rsync broke down..." >> $LOGDIR/uburelease.log
-        exit 1
+    ( echo "Ubuntu CD image sync failed. Please check logs."; \
+        egrep '^write failed|@ERROR' $LOGFILE ) | mail -s "Ubuntu release sync failed" $EMAIL
+    echo "$(date -R): Ubuntu releases CD images sync failed."
+    exit 1
 fi
 
+echo "Ubuntu release CD image sync completed."
+
+echo "$(date -R): Releasing lock file..."
 rm -f $LOCK > /dev/null 2>&1
+
+echo "$(date -R): Time-stamping trace file..."
 date -u > "${UBUREL_DIR}/.trace/${HOSTNAME}"
+
+echo "$(date -R): Ubuntu releases mirror operations completed."
